<?php require __DIR__ . '/../templates/header.phtml'; ?>
    <?php if (!empty($flashMessages)): ?>
        <div
            class="alert alert-<?= $key = key($flashMessages) ?>"
            role="alert">
                <?= $flashMessages[$key][0] ?>
        </div>
    <?php endif; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?=htmlspecialchars($url['name']); ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= $url['url_id']; ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($url['name']); ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= $url['url_created_at']; ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/<?= $url['url_id']; ?>/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($checks as $check) : ?>
                        <tr>
                            <td><?= $check['check_id']; ?></td>
                            <td><?= $check['status_code']; ?></td>
                            <td><?= $check['h1']; ?></td>
                            <td><?= $check['title']; ?></td>
                            <td><?= $check['description']; ?></td>
                            <td><?= $check['check_created_at']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </main>
<?php require __DIR__ . '/../templates/footer.phtml'; ?>