<?php require __DIR__ . '/../templates/header.phtml'; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-11 col-lg-9 col-xl-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row">
                        <div class="col-8">
                            <label for="text" class="visually-hidden">Url для проверки</label>
                            <input
                                type="text"
                                name="url[name]"
                                value="<?= $urlName ?? null; ?>"
                                class="form-control form-control-lg <?= isset($errors) ? 'is-invalid' : '';?>"
                                placeholder="https://www.example.com"
                            >
                            <?php if (isset($errors)) : ?>
                                <div class="invalid-feedback">
                                    <?= in_array('Urlname is required', $errors) ? 'URL не должен быть пустым' : 'Некорректный URL'; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <?php require __DIR__ . '/../templates/footer.phtml'; ?>
