<?= $this->fetch('header.phtml', ['choice' => 'view']) ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($urls as $url) : ?>
                        <tr>
                            <td><?= $url['id']; ?></td>
                            <td><a href="urls/<?= $url['id']; ?>"><?= htmlspecialchars($url['name']); ?></a></td>
                            <td><?= $url['last_check'] ?? null; ?></td>
                            <td><?= $url['status_code'] ?? null; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
<?= $this->fetch('footer.phtml'); ?>